name: protgen_env_conda
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - biopython=1.83=py38h01eb140_0
  - blas=1.0=mkl
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbd8a1cb_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.0.4=py38h578d9bd_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.7.1=py38h578d9bd_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_0
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.4=h3060b56_3
  - distro=1.9.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - ffmpeg=4.3.2=h37c90e5_3
  - filelock=3.16.1=pyhd8ed1ab_0
  - fmt=10.2.1=h00ab1b0_0
  - freetype=2.12.1=h267a509_2
  - frozendict=2.4.4=py38hfb59056_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py38h6a1700d_1
  - gnutls=3.6.13=h85f3911_1
  - h2=4.1.0=py38h578d9bd_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=he02047a_2
  - libcurand=10.3.5.147=he02047a_2
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=2.0.0=h14c3975_1000
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py38h5cd715c_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.20.3=h3eb15da_0
  - libsolv=0.7.29=ha6fb4c9_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - markupsafe=2.1.5=py38h01eb140_0
  - menuinst=2.1.2=py38h578d9bd_0
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.4.1=h7b32b05_0
  - pillow=9.4.0=py38hde6dc18_1
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - protobuf=3.20.3=py38h8dc9893_1
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py38h01eb140_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=hd12c33a_0_cpython
  - python_abi=3.8=7_cp38
  - pytorch=2.4.1=py3.8_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.2=h8c095d6_2
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.3=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py38h01eb140_0
  - ruamel.yaml.clib=0.2.8=py38h01eb140_0
  - scipy=1.10.1=py38h59b608b_3
  - sentry-sdk=2.19.2=pyhd8ed1ab_0
  - setproctitle=1.3.3=py38h01eb140_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - sympy=1.13.3=pypyh2585a3b_103
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.4.1=py38_cu118
  - torchtriton=3.0.0=py38
  - torchvision=0.19.1=py38_cu118
  - tqdm=4.67.1=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wandb=0.16.6=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - datasets==3.1.0
      - dill==0.3.8
      - einops==0.8.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - huggingface-hub==0.29.1
      - mmtf-python==1.1.3
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - packaging==24.2
      - pandas==2.0.3
      - progres==0.2.7
      - propcache==0.2.0
      - pyarrow==17.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyg-lib==0.4.0+pt24cu118
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - regex==2024.11.6
      - safetensors==0.5.2
      - six==1.17.0
      - tmtools==0.2.0
      - tokenizers==0.20.3
      - torch-cluster==1.6.3+pt24cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu118
      - torch-sparse==0.6.18+pt24cu118
      - torch-spline-conv==1.2.2+pt24cu118
      - transformers==4.46.3
      - tzdata==2025.1
      - xxhash==3.5.0
      - yarl==1.15.2
prefix: /gpfs/apps/MN5/ACC/MINIFORGE/24.3.0-0/envs/protgen_env_conda
